### ISSUE TITLE
Tracking Todos

### ISSUE THREAD

**Issue by spen** [spen/spen.github.io-react#69]
# Todos

- [ ] Components
  - [ ] Layout
    - [ ] Intro
    - [ ] Header
      - [x] Content/Intro toggle
      - [ ] Prev / Next buttons
    - [ ] Content Area
  - [ ] Pages
    - [ ] About
    - [ ] Blog
    - [ ] Projects
    - [ ] Contact
- [ ] Transitions
  - [ ] Intro / Content
  - [ ] Prev / Next
  - [ ] Touch Gestures
- [ ] Integrations
  - [ ] Wordpress Rest API
  - [ ] FormSpree
- [ ] Styling
  - [ ] Icons
    - [ ] Explore react libs that allow svg styles (shadows particularly)
    - [ ] Design custom icons?
  - [ ] Port Original
  - [ ] Styled Components!?
- [ ] State
  - [ ] Implement Redux
- [ ] Deployment
  - [ ] Automatic Publishing to GH pages
  - [ ] Port out as a WP theme

**Comment by idsn** [comment]
super cool project! will follow you!

**Comment by spen** [comment]
Thanks @idsn :) If you have any questions about any part feel free to ask them! Same goes for suggestions :D
